name: Parse OpenAI Pricing

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # Every day at 12:00 UTC

jobs:
  parse_pricing:
    name: Parse OpenAI Pricing Page
    runs-on: ubuntu-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install packges
        run: npm install

      - name: Install Playwright
        run: npx playwright-chromium install --with-deps

      - name: Scrape OpenAI pricing and save to JSON
        run: node scripts/parse-pricing.js

      - uses: stefanzweifel/git-auto-commit-action@v4
