name: Parse OpenAI Pricing

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # Every day at 12:00 UTC

jobs:
  parse_pricing:
    name: Parse OpenAI Pricing Page
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Playwright
        run: npx playwright-chromium install --with-deps

      - name: Install packges
        run: npm install

      - name: Scrape OpenAI pricing and save to JSON
        run: node scripts/parse-pricing.js

      - name: Commit and push results
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add openai-prices.json
          git commit -m "Update OpenAI pricing JSON" || echo "No changes to commit"
          git push